// GENERATED by scripts/measure-groups.mjs --write. Do not edit by hand.
//
// What each group of tools costs to enable, in tokens of tool definitions, measured by starting
// the server on the `search` profile and diffing tools/list around an enable_tools call.
//
// unreal_list_tools reports these so a model can choose what to switch on knowing the price.
// `npm run measure:groups` fails when they drift, because a stale number here is worse than none.

/** Tool-definition tokens standing on the `search` profile before anything is enabled. */
export const SEARCH_BASELINE_TOKENS = 1337;

/** Tokens added by enabling each group. */
export const GROUP_COST_TOKENS: Record<string, number> = {
  core: 10427,
  cpp: 417,
  anim: 343,
  edit: 3154,
  ui: 1942,
  materials: 1411,
  data: 4252,
  scene: 5937,
  maintenance: 1514,
};

/** Everything enabled at once, for the rare job that genuinely needs the whole surface. */
export const ALL_GROUPS_TOKENS = 30732;

/** Naming the eight tools one Blueprint feature needs, instead of enabling the `core` group. */
export const FEATURE_SET_TOKENS = 4650;

/** Standing cost of each preset, enabled on its own from the `search` baseline. */
export const PRESET_COST_TOKENS: Record<string, number> = {
  diagnose: 8441,
  feature: 7589,
  ui: 5931,
  data: 6526,
  cpp: 4084,
};
