// GENERATED by scripts/measure-groups.mjs --write. Do not edit by hand.
//
// What each group of tools costs to enable, in tokens of tool definitions, measured by starting
// the server on the `search` profile and diffing tools/list around an enable_tools call.
//
// unreal_list_tools reports these so a model can choose what to switch on knowing the price.
// `npm run measure:groups` fails when they drift, because a stale number here is worse than none.

/** Tool-definition tokens standing on the `search` profile before anything is enabled. */
export const SEARCH_BASELINE_TOKENS = 1135;

/** Tokens added by enabling each group. */
export const GROUP_COST_TOKENS: Record<string, number> = {
  core: 10504,
  ai: 294,
  anim: 306,
  cine: 299,
  cpp: 745,
  data: 4798,
  edit: 4330,
  input: 946,
  maintenance: 4452,
  materials: 1359,
  scene: 6611,
  ui: 1900,
  vfx: 315,
};

/** Everything enabled at once, for the rare job that genuinely needs the whole surface. */
export const ALL_GROUPS_TOKENS = 37993;

/** Naming the eight tools one Blueprint feature needs, instead of enabling the `core` group. */
export const FEATURE_SET_TOKENS = 4558;

/** Standing cost of each preset, enabled on its own from the `search` baseline. */
export const PRESET_COST_TOKENS: Record<string, number> = {
  diagnose: 10133,
  feature: 7551,
  ui: 5757,
  data: 6696,
  cpp: 4322,
};
